import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

const fixedSysExcelsior = localFont({
  src: "../fonts/Fixedsys-Excelsior-Regular.woff",
});
const modalzShort = localFont({
  src: "../fonts/modalz-short.woff2",
});
const modalzTall = localFont({
  src: "../fonts/modalz-tall.woff2",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={modalzShort.className}>{children}</body>
    </html>
  );
}
